# Generated by Django 3.2.9 on 2021-11-14 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='seat_map_detail',
            new_name='eat_map_detail',
        ),
    ]
